
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 03 17:43:42 CET 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 46;
  public static final int EQUALITY = 24;
  public static final int CONST = 9;
  public static final int LPAREN = 38;
  public static final int SEMI = 36;
  public static final int GREATER = 26;
  public static final int CONTINUE = 15;
  public static final int INTERFACE = 48;
  public static final int LESS = 28;
  public static final int FOR = 16;
  public static final int MINUS = 19;
  public static final int CHARACTER = 52;
  public static final int RPAREN = 39;
  public static final int STATIC = 17;
  public static final int AND = 30;
  public static final int RANGE = 13;
  public static final int LESSEQUAL = 29;
  public static final int OR = 31;
  public static final int BOOL = 50;
  public static final int COMMA = 37;
  public static final int CLASS = 7;
  public static final int INC = 32;
  public static final int DIV = 22;
  public static final int DOUBLEDOT = 34;
  public static final int PLUS = 18;
  public static final int MULTIPLY = 21;
  public static final int ASSIGN = 20;
  public static final int IF = 10;
  public static final int DOT = 35;
  public static final int INEQUALITY = 25;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int NUMBER = 49;
  public static final int MOD = 23;
  public static final int IDENT = 51;
  public static final int BREAK = 6;
  public static final int VOID = 5;
  public static final int GREATEREQUAL = 27;
  public static final int COLON = 53;
  public static final int UNION = 47;
  public static final int LBRACE = 42;
  public static final int ELSE = 8;
  public static final int LSQUARE = 40;
  public static final int READ = 12;
  public static final int WHILE = 45;
  public static final int RSQUARE = 41;
  public static final int RBRACE = 43;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int DEC = 33;
  public static final int DO = 44;
  public static final int PRINT = 3;
}

